version: "3.7"

services:
  goaccess-prometheus-exporter:
    build:
      dockerfile: Dockerfile
    environment:
      LOG_FILES: "*.log"
      TIMEZONE: "Etc/UTC"
    ports:
      - "9100:9100"
    volumes:
      - ./LOG_DIRECTORY:/opt/logs:ro